### ISSUE TITLE
Assertion error when running transcribe_audio.sh

### ISSUE THREAD

**Issue by tenvinc** [BreezeWhite/Music-Transcription-with-Semantic-Segmentation#12]
I used one of my .wav file as the input and tried the transcribe_audio with the checkpoint model from CheckPoint/MAPS_CFP_MPE/ but I got this error.

Model CheckPoint/MAPS_CFP_MPE loaded
Predicting...
Traceback (most recent call last):
  File "SingleSongTest.py", line 78, in <module>
    main(args)
  File "SingleSongTest.py", line 53, in main
    midi = MultiPostProcess(pred, mode="note", onset_th=args.onset_th, dura_th=0.5, frm_th=3, inst_th=1.1, t_unit=0.02)
  File "/media/tenvinc/New Volume/Music-Transcription-with-Semantic-Segmentation/project/postprocess.py", line 326, in MultiPostProcess
    assert((pred.shape[-1]-1)%ch_per_inst == 0)
AssertionError

I tried printing out the pred.shape and realized that it was 1 instead of 2 that it was expecting. Please help thanks:)

**Comment by tenvinc** [comment]
I used pred.shape[-1] instead of pred.shape[-1-1 and edited the rest of the code accordingly and it seemed to be able to give me an output midi.

![image](https://user-images.githubusercontent.com/32165733/87849799-0945e980-c91e-11ea-9e38-07664654cb19.png)

**Comment by BreezeWhite** [comment]
I've updated the code, please pull master branch into your local directory and then try again.
If there is still problems, feel free to open another issue, thx.
