### ISSUE TITLE
pred index 2 is out of bounds 

### ISSUE THREAD

**Issue by Abefocuson** [BreezeWhite/Music-Transcription-with-Semantic-Segmentation#3]
when running "SingleSongTest.py" ，I meet this error：

D:\Music-Transcription-with-Semantic-Segmentation-master\project\utils.py:304: ResourceWarning: unclosed file <_io.TextIOWrapper name='.\\CheckPoint\\MAPS_CFP_MPE\\arch.yaml' mode='r' encoding='cp936'>
  model = model_from_yaml(open(os.path.join(model_path, "arch.yaml")).read(), custom_objects=custom_layers)
2019-08-14 21:59:51.698793: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
model .\CheckPoint\MAPS_CFP_MPE\ loaded
Predicting...
pred.shape
(4096, 352, 2)
Traceback (most recent call last):
  File "SingleSongTest.py", line 108, in <module>
    main(args)
  File "SingleSongTest.py", line 86, in main
    notes, midi = PostProcess(pred)
  File "D:\Music-Transcription-with-Semantic-Segmentation-master\project\postprocess.py", line 267, in PostProcess
    ch = pred[:,:,2]
IndexError: index 2 is out of bounds for axis 2 with size 2

the shape of pred is [*,*,2] , so the index 2 is out of bounds.

How can I solve this problem?

Thanks.

**Comment by BreezeWhite** [comment]
This model predict on frame-level, so there would only be 2 channels. One for "off", and the other one "on". 
And the PostProcess function was designed to process on 3 channels, which is incompatible with this model.
If you just want to listen to the transcription result, I have just uploaded a colab for a quick taste, and you can find the URL in README.

Hope this helps you^^
