### ISSUE TITLE
The result of the model you provided

### ISSUE THREAD

**Issue by xk-wang** [BreezeWhite/Music-Transcription-with-Semantic-Segmentation#6]
I fixed the bugs in your code and got the output midi files. Then I transformed the midi files to txt files contain onset, offset, pitch. Then I used mir_eval to evaluate your results on the note level and what I got was bellow:

note : f-0.130963044896 p-0.133633039813 r-0.131702754674

I doubted the result on frame level in your paper.

**Comment by BreezeWhite** [comment]
Hi, I've recently encounter a similar situation, and I found there are some bugs of the code and the checkpoints. I will update them near these days. Sorry for the inconvenience.

Some remindness that if you try to reproduce the result reported on the paper, you should enter the folder *v1* and use the *Predict.py*, *Evaluation.py*. There has been some update of the code since the paper being submitted, and the experiment code used then are placed in *v1* folder now.

**Comment by xk-wang** [comment]
OK, thank you. I used the google colab to predict the ENSTDkCl subset of MAPS dataset and I got the midi files. Next I use the&nbsp;pretty_midi to transform midi files to result files containing onset, offset, pitch of each note. Then I used mir_eval to evalute the result files using the ENSTDkCl txt files as labels. I evaluated the result files at note level which means only considering onset and pitch and ignoring offset time. The average&nbsp; F1 value of 30 tracks of&nbsp; ENSTDkCl subset is 67%. I wonder why you get a high score at frame level but a low score at note level.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Derek-Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 上午10:24
收件人:&nbsp;"BreezeWhite/Music-Transcription-with-Semantic-Segmentation"<Music-Transcription-with-Semantic-Segmentation@noreply.github.com&gt;;
抄送:&nbsp;"王先科"<xk_wang@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [BreezeWhite/Music-Transcription-with-Semantic-Segmentation] The result of the model you provided (#6)




Hi, I've recently encounter a similar situation, and I found there are some bugs of the code and the checkpoints. I will update them near these days. Sorry for the inconvenience.
 
Some remindness that if you try to reproduce the result reported on the paper, you should enter the folder v1 and use the Predict.py, Evaluation.py. There has been some update of the code since the paper being submitted, and the experiment code used then are placed in v1 folder now.
