### ISSUE TITLE
I found Miss 2

### ISSUE THREAD

**Issue by HiroshiYamamoto47** [BreezeWhite/Music-Transcription-with-Semantic-Segmentation#9]
README.md > Usage > Training 
`python3 TrainModel.py MusicNet \
    --dataset-path <path/to/extracted/feature> \
    -o <output/model/name>`
"-o" is not defined in TrainModel.py, line 164.

or correct writing is 
 `python3 TrainModel.py MusicNet \
     <output/model/name> \
     --dataset-path <path/to/extracted/feature>`

**Comment by BreezeWhite** [comment]
Thank you for your reminding. I'll fix it later.
